name: "Stockopedia's Terraform runner"
description: "GitHub Action that expores the Stockopedia Terraform stack, uses the changed file list in the current PR, and runs `terraform plan` on each changed stack."
author: "Andrei Ruse"
inputs:
  CHANGED_FILE_LIST:
    description: "A comma separated list of file paths, indicating files that have changed in the current PR. If all files in the repository are passed in, this will re-plan the entire stack."
    default: "[]"
    required: true
  BASE_DIRECTORY:
    description: "The base directory of the terraform project. Used to look up the ./environments/ folder under it."
    default: "/app"
    required: false
  DISABLE_NON_AWS_CHANGES:
    description: "Can have any value. If present, only aws provided layers will be considered by terraform."
    default: ""
    required: false
  APPLY_MODE:
    description: "Determines whether the script should also run 'terraform apply' after the 'terraform plan' step. Disabled by default."
    default: "false"
    required: false
outputs:
  terraform_plan_output:
    description: "Output from the Terraform Plan action(s). If multiple plans ran, the plans will be separated by 2 line separators."
  terraform_apply_output:
    description: "Output from the Terraform Apply action(s). This will be empty if APPLY_MODE was not set to true. If multiple plans ran, the plans will be separated by 2 line separators."
  terraform_error_output:
    description: "Error outputs from any of the steps (Init, Plan, Apply). If multiple plans ran, the plans will be separated by 2 line separators."
runs:
  using: "docker"
  image: "Dockerfile"
