name: Integration Test
on: [push]
jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: Stockopedia/action-run-terraform-on-pr@master

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.terraform_error_output }}" == ""
