name: Run Unit Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - uses: actions/checkout@master
      - name: Check Python typing using MyPy
        run: |
          pip install mypy
          mypy src/
      - name: Run Unit Test
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          cd test
          pytest .
